### ISSUE TITLE
BLE pluggin - cordova-plugin-bluetoothle

### ISSUE THREAD

**Issue by 1112403** [ionic-team/ionic-native#1052]
We already saw one available BLE plugin wrapped in ionic native but unfortunately my company does not use that plugin but this one: https://github.com/randdusing/cordova-plugin-bluetoothle

So could you please help to integrate this plugin into ionic native please?

or there is quick/dirty way to use it?

Thank you very much

Vuong Nguyen
EMSA TECHNOLOGY

**Comment by ihadeed** [comment]
We'll look into it. 

For now, if you need to use it with Ionic 2, you can do the following:

1. Add this line at the top of every page where you wish to use the plugin to get rid of IDE errors:
```
declare var bluetoothle: any;
```

2. Use the plugin as instructed by their documentation, you will have to use callback functions since that's how their plugin works.

**Comment by scalpel4k** [comment]
I would also love to see it. It seems to have so many more features ....

**Comment by elovin** [comment]
I would also like to see this plugin being supported as it seems to be the only Bluetooth plugin with peripheral functionality e.g. advertisement  !

**Comment by elovin** [comment]
If you want to know how to use this plugin in ionic 3, take a look at this stack overflow question [](https://stackoverflow.com/a/48208531/6853836)

**Comment by tempestwf** [comment]
Hi, that link doesn't work to stackoverflow. Can you please repost it?

**Comment by danielsogl** [comment]
Plugin added
