### ISSUE TITLE
Ionic Native's SpinnerDialog does not support W10 UWP  / IE11 / EDGE

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#1603]
_From @tryadelion on May 24, 2017 9:46_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ X] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic's Native SpinnerDialog plugin does not work on Windows 10 UWP platform, and there is no official alternative.

"Bug report" -> https://github.com/Paldom/SpinnerDialog/issues/43

**Expected behavior:**

Provide an alternative ionic native plugin implementation that works on every supported ionic platform 6 document how to perform a similar action on W10 UWP / IE11/ edge.

_Copied from original issue: driftyco/ionic#11771_

**Comment by piotrowski** [comment]
@tryadelion Ionic Native can only implement Cordova plugins that are there - and it seems there is no widely used and supported Cordova spinner plugin that supports all platforms, correct? Which one would you suggest to be implemented?

**Comment by tryadelion** [comment]
https://github.com/greybax/cordova-plugin-native-spinner  this one might work but with the new CLI  i find myself unable to test it, it's like it was not being installed. If it works, it could be the one.

**Comment by danielsogl** [comment]
Do you talk about the Cordova CLI or about the Ionic CLI? You have to run ionic cordova plugin add XYZ

But because there is no native wrapper you have to follow the official repo docs to use the plugin.

**Comment by tryadelion** [comment]
i ran ionic cordova xxxxxxxxx

should i run the prepare part too? isn't that useless now in 2.x/3.x?

**Comment by piotrowski** [comment]
Maybe the API of this plugin is similar enough to be used with the same Ionic Native wrapper:

https://github.com/greybax/cordova-plugin-native-spinner is a fork of https://github.com/ravi013/cordova-plugin-spinnerdialog which is based on https://github.com/Paldom/SpinnerDialog which has an Ionic Native wrapper at https://ionicframework.com/docs/native/spinner-dialog/

(What a mess...)

**Comment by tryadelion** [comment]
@piotrowski  It didn't work, it kept telling me via the JS console that i should install the parldom one. It might be related to the name, i am not sure  how the wrapper works.

**Comment by greybax** [comment]
Guys @tryadelion and @piotrowski let me explain some things.
I'm author of https://github.com/greybax/cordova-plugin-native-spinner. This is one of the lot of [forks](https://github.com/Paldom/SpinnerDialog/network) of https://github.com/Paldom/SpinnerDialog. I've done it one because seems, that main repository (Paldom/SpinnerDialog) looks like is not supporting for a very long time...

I've just forked and applied some fixes and improvements which was made in https://github.com/Paldom/SpinnerDialog and published them as [npm package](https://www.npmjs.com/package/cordova-plugin-native-spinner).

Ionic native are using now [Paldom/SpinnerDialog](https://github.com/Paldom/SpinnerDialog) by default, but this plugin doesn't support Windows platform and latest version of WP. So that's why you probably have issues with these platforms. So now I can see only one solution of this issue. 
Just install and use `cordova plugin add cordova-plugin-native-spinner` separately while it will not added by default in ionic-native or [Paldom/SpinnerDialog](https://github.com/Paldom/SpinnerDialog) while not accepted PR's which he has in repo.

**Comment by piotrowski** [comment]
@greybax Great that you jump in here! Ahh, now I se, you are 4 levels down from Paldom/SpinnerDialog. Can we somehow compare your repo to the great-great-grandmother Paldom/SpinnerDialog in Github UI? If there is nothing incompatible, I think it should be fine to maybe change the Ionic Native plugin to your repo.

**Comment by greybax** [comment]
@piotrowski yes, It's perfectly fine for me

**Comment by greybax** [comment]
@piotrowski for comparing repos in Github UI I think you can use this page https://github.com/Paldom/SpinnerDialog/compare/master...greybax:master

**Comment by tryadelion** [comment]
changes seem quite positive, would be nice to have this plugin as main one instead, @piotrowski .

**Comment by piotrowski** [comment]
Well, somebody make a PR for the plugin, add that link into the description and the people responsible will look into it!

**Comment by tryadelion** [comment]
_**somebody**_

**Comment by greybax** [comment]
I will create the PR with these changes

**Comment by greybax** [comment]
sent PR
