### ISSUE TITLE
InAppBrowser OAuth Pattern breaks android - works for iOS

### ISSUE THREAD

**Issue by tharrington** [ionic-team/ionic-native#1712]
[ X ] bug report
[ ] feature request

Current behavior:
In app browser cannot handle redirects on Android. Works fine for iOS. OAuth pattern.

Expected behavior:
Browser would load to the correct page. 

Steps to reproduce:

I am using cordova inappbrowser in ionic 2. I open a browser window and listen to onload: 

```
    let browser = this.iab.create(loginUrl, "_blank", "location=no,toolbarposition=top,closebuttoncaption=Cancel,clearsessioncache=yes,clearcache=yes");
    
    browser.on("loadstart")
            .subscribe(
              (event) => {
                console.log('### load start event');
                if(event.url.substr(0, redirectUri.length) === redirectUri) {
                  this.handleLoginEvent(event.url, browser);
                }
              },
              err => {
                console.log("InAppBrowser Loadstop Event Error: " + err);
              }
            );

```

The url in loginUrl forces a redirect for an oauth pattern. In iOS, everything works fine, but on android the page simply doesn't load. The emulator shows the correct URL but the page itself won't load - just a whitescreen. It will load if I simply open https://google.com. 

Here is my $ ionic info:

    Your system information:
    
    Cordova CLI: 7.0.0 
    Ionic Framework Version: 3.1.1
    Ionic CLI Version: 2.2.3
    Ionic App Lib Version: 2.2.1
    Ionic App Scripts Version: 1.3.7
    ios-deploy version: 1.9.0 
    ios-sim version: 4.1.1 
    OS: macOS Sierra
    Node Version: v6.9.4
    Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by matthijsbierman** [comment]
We've seen a similar problem. In our case the server was missing some intermediate SSL certificates. You can check if that's the case for your server with https://www.ssllabs.com/ssltest/analyze.html.

**Comment by josterfeld** [comment]
I am experiencing the same issue on Android. The inappbrowser works on a Samsung Galaxy J3, but does not work on a Google Pixel; I get a white screen with no page loaded. I tested out OAuth2 server on the provided site and got an A rating, so I don't expect the issue to be SSL certs.

**Comment by lettucemode** [comment]
My team ran into a similar problem, so I am leaving our solution here for posterity, in case it helps anyone else who stumbles across this issue while researching.

For context - there has been some kind of change in how TLS certificates are bundled and how clients (browsers, etc.) resolve and validate that certificate bundle. Newer clients are able to dynamically look up and validate certs that are NOT included in the bundle (in our case, a .pfx file), such as the CA root cert. Older clients, such as our mutual friend InAppBrowser, apparently are not. I tried to figure out exactly what browser & version & etc. the InAppBrowser represents, but didn't get anywhere before moving on.

You can check whether or not the TLS cert/bundle you have placed on your backend (whether that's a gateway/load balancer, single server, or whatever) contains a root CA cert in it with these tools:
- https://www.ssllabs.com/ssltest/analyze.html
-- matthijsbierman suggested this above, but in our case, it wasn't very explicit about whether the root was included. If you see certification paths that include "additional download" in order for the test to complete & validate the cert chain, that is a good sign that older clients such as InAppBrowser will not work.
- https://www.digicert.com/help/
-- this is mostly for Digicert certs, but this tool specifically calls out intermediate certificates, and will have a big red error at the bottom that says "TLS Certificate is not trusted" if your bundle doesn't directly include a root CA or otherwise well-known trusted cert, even if you aren't using Digicert, which is nice.

We resolved the issue by recreating the bundle manually and including the root cert in it. Our cert vendor has a tool for this, but you can also use openssl or other tools to do so ([example](https://blog.brooksjc.com/2022/04/15/creating-certificate-bundles-for-application-gateway/)).

After reapplying the cert to our gateway, the issue was resolved for InAppBrowser.
