### ISSUE TITLE
Device properties are empty in browser

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic-native#1752]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Using `{Device} from '@ionic-native/device';`, I got an object with empty values in browser.
![image](https://user-images.githubusercontent.com/4112256/27771616-80d1fd56-5f52-11e7-9065-a3a755a0b2e1.png)

**Expected behavior:**
I should have an object with browser values, as https://ionicframework.com/docs/native/device/ states it is supported.
![image](https://user-images.githubusercontent.com/4112256/27771618-914d3952-5f52-11e7-9e8f-a2666750ae53.png)

**Steps to reproduce:**
Add Device plugin in app.module.ts as a provider, then load it in a constructor and `console.log(this.device)`.

**Comment by janpio** [comment]
How did you build or run the app?

**Comment by ihadeed** [comment]
Looks like you're running on `ionic serve`. That doesn't count as a browser platform. To run on browser platform you need to run `cordova run browser`. 

Ionic Native plugins don't work on `ionic serve`. I think the only plugin that works is Geolocation, because it follows the standard WebAPI that's supported by all browsers.

**Comment by HugoHeneault** [comment]
Oh, thanks for that quick explanation. I haven't found anything about this in the docs. Maybe it should be stated more clearly?
