### ISSUE TITLE
Display contacts images

### ISSUE THREAD

**Issue by MurhafSousli** [ionic-team/ionic-native#1808]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**

contact photos response doesn't have a valid img path
```
photoObject: {
    id: "8", 
    pref: false, 
    type: "url", 
    value: "content://com.android.contacts/contacts/1/photo"   // <= not a valid img path
}
```

**Expected behavior:**

 Ability to display contact image

**Steps to reproduce:**

```html
<ion-list>

  <button ion-item *ngFor="let contact of list">

    <ion-avatar item-start>
      <img *ngIf="contact?.photos" [src]="contact.photos[0].value"/>
    </ion-avatar>

    <div>
      <p> {{ contact.displayName || contact.phoneNumbers[0].value }} </p>
    </div>

  </button>

</ion-list>
```
```ts
 constructor(public contacts: Contacts) {

   contacts.find(['displayName', 'phoneNumbers'], {multiple: true})
      .then((contacts) => {
          this.list = contacts;
      });
}
```

**Other information:**

[more info on SO](https://stackoverflow.com/questions/45128807/how-to-get-contacts-images-ionic-3)

**package.json info:**

```json
"cordova-plugin-contacts": "^2.3.1",
"@ionic-native/contacts": "^4.0.0"
```

![test](https://i.stack.imgur.com/0vjF4.png)

**Comment by Pezhvak** [comment]
i'm having the same problem, how did you solve this?

**Comment by chrisgriffith** [comment]
This actually is NOT an Ionic issue, but rather one with the plugin itself (which Ionic did not write).

Please note that this plugin has the following notice:
**Deprecation Notice**
This plugin is being deprecated. No more work will be done on this plugin by the Cordova development community. You can continue to use this plugin and it should work as-is in the future but any more arising issues will not be fixed by the Cordova community.

**Comment by Pezhvak** [comment]
@MurhafSousli well i'm thinking the same. thanks for your respond
@chrisgriffith please do update the documentation about this. i tried for 5-6 hours yesterday to make it work with no luck.
