### ISSUE TITLE
QRScanner is missing 'destroy'

### ISSUE THREAD

**Issue by andrews05** [ionic-team/ionic-native#1916]
The ionic-native QRScanner implementation doesn't appear to support the [destroy](https://github.com/bitpay/cordova-plugin-qrscanner#destroy) method. I believe this method is important to turn off the camera and save battery once you're done scanning. Unless there's something I'm missing/not understanding?

**Comment by Inconspicuously** [comment]
Agreed. This is an issue I ran into when trying to solve another problem https://forum.ionicframework.com/t/qrscanner-camera-preview-is-not-removed/105104

I've made the required changes and have submitted a pull request. In the meantime you can add the destroy method manually by editing the index.d.ts and index.metadata.json files.

**Comment by andrews05** [comment]
@Inconspicuously Thanks! Your PR appears to be closed?

**Comment by Inconspicuously** [comment]
Yes, I realised it wasn't building properly and then did a fantastic job of messing up the merges, which finally resulted in me starting over with a new repository. I have now figured out how I'm supposed to test it properly before attempting to do a PR.
This is my first ever plugin fix and PR, and although it shouldn't be all that complicated, I've learned the hard way that there are some pretty vital steps you need to take. 
I closed the PR so that I could get everything fixed up properly first. Please excuse my inexperience, I come from a non technical background and frequently find that I have large gaps in my education regarding certain common technologies, such as github. I'll get there eventually :)
I'll (hopefully) have everything fixed tomorrow.

**Comment by andrews05** [comment]
No worries :)
I don't expect this to appear in an official update anytime soon anyway, so in the meantime I've just calling `QRScanner.destroy()` directly.
