### ISSUE TITLE
Mark contacts and globalization as deprecated

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic-native#2235]
Both plugins are deprecated since the latest releases. We should mark them as deprecated.

You can read more about the changes here: https://cordova.apache.org/news/2017/11/27/Deprecation-of-cordova-contacts-plugin.html

**Comment by vandres** [comment]
@ihadeed What is the alternative for using the contact plugin?

**Comment by ihadeed** [comment]
@vandres you can still use the plugin as-is. Cordova team is just not going to take care of any issues or updates from this point.

AFAIK they maintain plugins until their API becomes part of the web. In this case, the contacts API will never have a web API because of privacy issues; therefore, they're discontinuing the project immeadieatly. 

At this point I'd keep an eye out for a new maintained fork, or an alternative plugin.

**Comment by vandres** [comment]
@ihadeed Thank you for the information. Maybe it would be nice to have this also written in the deprecation note, as normallly there is an alternative when something gets deprecated
