### ISSUE TITLE
[firebase-auth]  SMS verification code / Incorrect variable type 

### ISSUE THREAD

**Issue by patrickjvieira** [ionic-team/ionic-native#2967]
Firebase Authenthication require a string type not a number type on sms verification code. Sometime Firebase sends the code starting with zero, (E.g. 012345) so, number type will be casted to "12345" instead of "012345". It results in "Incorrect code message".

Incorrect type:
https://github.com/ionic-team/ionic-native/blob/49d7ca7375d405daacf61f0b7264947e90a67f4c/src/%40ionic-native/plugins/firebase-authentication/index.ts#L112

Firebase code Reference:
https://github.com/firebase/snippets-android/blob/7d03e65500cd63a26e5bf9b8b6e4d3ab9479806a/auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java#L548

**Comment by Drmorph** [comment]
is this issue is planned to be fixed ?
this make an error on using the ionic supported "firebase-authentication"

[](https://ionicframework.com/docs/native/firebase-authentication
)https://ionicframework.com/docs/native/firebase-authentication

issue was reported by some user on:

[](https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/53)https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/53

**Comment by xtarx** [comment]
Hello, any updates regarding the problem?  The required type for the smsCode is a string instead of number.

**Comment by xtarx** [comment]
I have created  a PR fix for this issue https://github.com/ionic-team/ionic-native/pull/3354
