### ISSUE TITLE
Who is responsible for developing the enterprise plugins and how to contribute?

### ISSUE THREAD

**Issue by tomavic** [ionic-team/ionic-native#3150]
May I know how to contribute to the enterprise plugins development? As there is no reference in docs pointing to something like that.

**Comment by dotNetkow** [comment]
Hi, the Ionic team builds and maintains them. Since they are paid solutions, contribution isn't open to the community. We appreciate your interest though!

If you happen to be a customer of ours, find an issue or have a feature request, you can send an email to our [support team](mailto:support@ionic.io) and they'll review it then coordinate further.
