### ISSUE TITLE
About fingerprint-aio 3.0

### ISSUE THREAD

**Issue by book12085** [ionic-team/ionic-native#3229]
When can I upgrade fingerprint-aio version 3.0?

Best Regards

**Comment by akshaydwivedi29** [comment]
i tested the fingerprint-aio 3.0 on a fresh project & it works well. So i guess it's safe to use 3.0 **but** on an existing project you might landup in some build issues due to conflicts with other plugins which you have to solve it manually.
have look at the issue posted on https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/207

**Comment by book12085** [comment]
tks
