### ISSUE TITLE
@ionic-native/purchases for cordova-plugin-purchases is not compatible with the latest version of the plugin

### ISSUE THREAD

**Issue by yurizekb** [ionic-team/ionic-native#3266]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The @ionic-native/purchases and manual are not compatible with the latest version of the plugin
https://ionicframework.com/docs/native/purchases
Breaking changes were made in version 1.0.0 of the plugin 
https://github.com/RevenueCat/cordova-plugin-purchases/releases/tag/1.0.0

**Expected behavior:**
The @ionic-native/purchases is compatible with the latest version of the cordova-plugin-purchases

**Steps to reproduce:**
Сomplete all the steps from the documentation 
https://ionicframework.com/docs/native/purchases
until step 3 "Displaying Available Products":

this.purchases.getEntitlements()
     .subscribe(entitlements => ,
                error => );

Error: Property getEntitlements does not exist on type Purchases

**Comment by Prateek-Kickdrum** [comment]
Do we have any recent version to update Native Purchase plugin compatible with Latest Cordova. 

Cordova latest - 1.0.4 (https://github.com/RevenueCat/cordova-plugin-purchases)
And following this are updated in the latest build.

Support for new Offerings system.
- Deprecates makePurchase methods. Replaces with purchasePackage
- Deprecates getEntitlements method. Replaces with getOfferings
- See our migration guide for more info: https://docs.revenuecat.com/v3.0/docs/offerings-migration
- Updates to BillingClient 2.0.3. If finishTransactions is set to false (or observerMode is true when configuring the SDK), this SDK won't acknowledge any purchase and you have to do it yourself.
- Adds proration mode support on upgrades/downgrades
- Adds more PurchaserInfo missing properties. activeEntitlements, expirationsForActiveEntitlements and purchaseDatesForActiveEntitlements have been removed from PurchaserInfo
- intro_price, intro_price_period_number_of_units and intro_price_cycles are a number now or null instead of empty strings, intro_price_period_unit can also be null.

RevenueCat
Offerings Migration Guide
Migrating to Offerings from a legacy setup


Please reply if we have any update plans.?

**Comment by vegaro** [comment]
Hi! I actually worked last night on updating the plugin to the latest cordova-plugin-purchases. I will be testing the update and opening the update PR today.

**Comment by Prateek-Kickdrum** [comment]
Great Thanks, appreciated.

Can you just let me know the tentative dates which it will be available? I can update it on my working list, for my status.

**Comment by vegaro** [comment]
Just opened https://github.com/ionic-team/ionic-native/pull/3301

**Comment by vegaro** [comment]
The PR got merged to master @Prateek-Kickdrum @yurizekb . I believe this can be closed now

**Comment by Prateek-Kickdrum** [comment]
Yes, Just one request. 
I suppose the below document require update as well with the latest usage.
https://ionicframework.com/docs/native/purchases

I am not sure who is going to do it.
